### ISSUE TITLE
Invalid type for taskID

### ISSUE THREAD

**Issue by SergeyDonskoy** [robdimsdale/wundergo#2]
Counter of tasks on Wunderlist became bigger, than `uint` range in Go, so it's become impossible to work with. Could you please change type for uint64 or uint? Now I have such error during task processing
`strconv.ParseUint: parsing "4401114685": value out of range`

**Comment by robdimsdale** [comment]
@SergeyDonskoy this repository is no longer maintained. I updated the README to reflect this.
